packages:
  cachy:
    - 'act'
    - 'alacritty'
    - 'ansible'
    - 'anydesk-bin'
    - 'asdf-vm'
    - 'base-devel'
    - 'brave-bin'
    - 'claude-code'
    - 'dbeaver'
    - 'discord'
    - 'docker'
    - 'docker-compose'
    - 'firefox'
    - 'fprintd'
    - 'git'
    - 'glib'
    - 'glib2-devel'
    - 'gnome-boxes'
    - 'gobject-introspection'
    - 'gtk-doc'
    - 'htop'
    - 'hub'
    - 'intellij-idea-community-edition'
    - 'meson'
    - 'neofetch'
    - 'neovim'
    - 'nvtop'
    - 'obs-studio'
    - 'openai-codex'
    - 'opencode'
    - 'pam_wrapper'
    - 'postgresql'
    - 'postgrest'
    - 'prettier'
    - 'python-crcmod'
    - 'python-pip'
    - 'python-pipx'
    - 'python-pyusb'
    - 'python-uv'
    - 'qbittorrent'
    - 'qwen-code'
    - 'ripgrep'
    - 'starship'
    - 'ttf-jetbrains-mono-nerd'
    - 'visual-studio-code-bin'
    - 'vlc'
    - 'vlc-plugins-all'
    - 'zsh-antidote'
